#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)

    while(dados.find(b"\n") != -1):
        comando = dados.split(b'\n')
        mensagemCompleta = conexao.get_mensagem() + comando[0]
        if mensagemCompleta.startswith(b"PING"):
            args = mensagemCompleta.split(b" ")
            mensagemCompleta = b":server PONG server :" + args[1] + b"\n"

        conexao.remover_comando()
        newDados = dados.replace(comando[0] + b"\n", b"")
        dados = newDados
        conexao.enviar(mensagemCompleta)  
    
    if dados != "":
        conexao.salvar_mensagem_incompleta(dados) 
        

def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
